version: '3.8'

services:
  # Backend service (Laravel)
  ecodeli-backend:
    build:
      context: ./ecodeli-backend
      dockerfile: Dockerfile
    container_name: ecodeli-backend
    restart: unless-stopped
    volumes:
      - ./ecodeli-backend:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - ecodeli-network

  # Frontend service (React)
  ecodeli-frontend:
    build:
      context: ./ecodeli-frontend
      dockerfile: Dockerfile
    container_name: ecodeli-frontend
    restart: unless-stopped
    volumes:
      - ./ecodeli-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - ecodeli-backend
    networks:
      - ecodeli-network

# Networks
networks:
  ecodeli-network:
    driver: bridge
